POST https://mp-sg-openapi.auto.mydlink.com/me/nvr/event/list?access_token=ezDMdImFD3tIHkB6KJcBszX8qdajjZlF
Content-Type: application/json

{
  "data": {
    "end_ts": 1707633900000,
    "start_ts": 1707633840000
  }
}